sudo: required
dist: trusty
language: node_js

node_js:
  - '10.9.0'

env:
  - TASK=test
  - TASK=lint
  - TASK=build
  - TASK=site:build

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

git:
  depth: 1

before_install:
  - set -e
  - export NG_CLI_ANALYTICS=ci
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm run $TASK
  - |
    if [ "$TASK" = "test" ]; then
      cat ./coverage/lcov.info | ./node_modules/.bin/codecov
    fi
