name: Deploy

on: push

jobs:
  doc:
    # if: "startsWith(github.event.commits[0].message, 'release')"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: install
        run: npm install

      - name: comment_on_github
        run: |
          node ./scripts/ci/github-comment.js "[Preview Preparing...](https://github.com/cipchk/ngx-weui/pull/${PR}/checks)"
        env:
          PR: ${{ steps.findPr.outputs.number }}
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: build
        run: |
          npm run site:init && ng build --prod --base-href /ngx-weui/
          cp ./dist/index.html ./dist/404.html
          ls ./dist

      - name: deploy-to-gh-pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
        with:
          emptyCommits: false

      - name: deploy-to-surge-pre
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: '/ngx-weui/'
          replace: '/'
          include: '\.html$'

      - name: deploy-to-surge
        uses: yohix/deploy-surge@v1.0.0
        with:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          DOMAIN_NAME: 'https://preview-${{ steps.findPr.outputs.number }}-ngx-weui.surge.sh'
          BUILD_DIRECTORY: ./dist

      - name: deploy-to-surge-release
        if: "startsWith(github.event.commits[0].message, 'release')"
        uses: yohix/deploy-surge@v1.0.0
        with:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          DOMAIN_NAME: 'https://ngx-weui.surge.sh'
          BUILD_DIRECTORY: ./dist

      - name: comment_on_github
        run: |
          node ./scripts/ci/github-comment.js "[Preview is ready!](https://preview-${PR}-ngx-weui.surge.sh)"
        env:
          PR: ${{ steps.findPr.outputs.number }}
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - uses: actions/checkout@v1
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitee.com:cipchk/ngx-weui.git
          ssh_private_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
