name: Deploy

on: push

jobs:
  website:
    # if: "startsWith(github.event.commits[0].message, 'release')"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: npm install

      - name: build
        run: |
          npm run site:build
          cp ./dist/index.html ./dist/404.html

      - name: deploy-to-gh-pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
        with:
          emptyCommits: false

      # - name: deploy-to-surge-pre
      #   uses: jacobtomlinson/gha-find-replace@master
      #   with:
      #     find: '/delon/'
      #     replace: '/'
      #     include: '\.html$'

      - name: deploy-to-surge
        uses: yohix/deploy-surge@v1
        with:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          DOMAIN_NAME: https://ngx-weui.surge.sh
          BUILD_DIRECTORY: ./dist

      - uses: actions/checkout@v1
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitee.com:cipchk/ngx-weui.git
          ssh_private_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
